#pragma once

#ifndef ETERNAL_USE_DXMATH_TYPES
#define ETERNAL_USE_DXMATH_TYPES					(1)
#endif

#ifndef ETERNAL_USE_CFILE
#define ETERNAL_USE_CFILE							(!ETERNAL_PLATFORM_ANDROID)
#endif

#ifndef ETERNAL_USE_ANDROID_ASSET_MANAGER_FILE
#define ETERNAL_USE_ANDROID_ASSET_MANAGER_FILE		(ETERNAL_PLATFORM_ANDROID)
#endif

#ifndef ETERNAL_USE_STD_PARALLEL
#define ETERNAL_USE_STD_PARALLEL					(1)
#endif
